$ErrorActionPreference = "Stop"
$enc = [System.Text.Encoding]::GetEncoding(936)
$file = "D:\dsh-project\LawnProject\src\Lawn\ThirtyFlags.cpp"
$txt = [System.IO.File]::ReadAllText($file, $enc)
$eol = if ($txt.IndexOf("`r`n") -ge 0) { "`r`n" } else { "`n" }

# ---------------------------------------------------------------- 1) ctor init
$cOld = "    mLostLanes = 0;" + $eol + "}"
if ($txt.IndexOf($cOld) -lt 0) { Write-Host "FAIL ctor anchor"; exit 1 }
$cNew = @(
  '    mLostLanes = 0;',
  '',
  '    mBossPhase = 0;',
  '    mBossID = -1;',
  '    mBossSkillTimer = 0;',
  '    mBossWarnTimer = 0;',
  '    mBossWarnSkill = 0;',
  '    mBossWarnRow = 0;',
  '    mBossSelfDestruct = 0;',
  '    mBossEmpTimer = 0;',
  '    mBossRoarTimer = 0;',
  '    mBossDomainTimer = 0;',
  '}'
) -join $eol
$txt = $txt.Replace($cOld, $cNew)
Write-Host "OK ctor init"

# ---------------------------------------------------------------- 2) boss module appended before ThirtyFlagsDrawBackdrop
$anchor = "void ThirtyFlagsDrawBackdrop(Board* theBoard, Graphics* g)"
$ai = $txt.IndexOf($anchor)
if ($ai -lt 0) { Write-Host "FAIL draw anchor"; exit 1 }

$bossLines = @(
  '// ====================================================================================================',
  '// Final boss - "Doom Mech" (plan chapter 8)',
  '//',
  '// The stock ZOMBIE_BOSS already provides stomp / bungee / head-spit skills driven by DamageIndex,',
  '// so this layer only adds what the plan asks for on top of it:',
  '//   * a shared 3-phase health pool with an invulnerable phase transition,',
  '//   * a telegraph-then-strike skill loop keyed to the current phase,',
  '//   * P3 self destruct countdown.',
  '// All effects reuse vanilla primitives (KillAllPlantsInRadius / AddZombieInRow / plant row rewrite),',
  '// so no new art, animation or sound is required.',
  '// ====================================================================================================',
  '',
  'enum ThirtyFlagsBossSkill',
  '{',
  '    TF_BOSS_SKILL_NONE = 0,',
  '    TF_BOSS_SKILL_SLAM,             // P1: crush a 2x2 block of plants',
  '    TF_BOSS_SKILL_HORDE,            // P1: summon a wave of elites down two lanes',
  '    TF_BOSS_SKILL_TERRAIN,          // P2: turn a whole row into water',
  '    TF_BOSS_SKILL_EMP,              // P2: disable all shooters for 10s',
  '    TF_BOSS_SKILL_ROAR,             // P2: board-wide zombie speed +50% for 8s',
  '    TF_BOSS_SKILL_ROAR_ULTIMATE,    // P3: destroy every plant in the frontmost column',
  '    TF_BOSS_SKILL_DOMAIN            // P3: zombies lifesteal and leave poison',
  '};',
  '',
  'constexpr int TF_BOSS_VANILLA_PHASE_HEALTH = TF_BOSS_HEALTH / 3;',
  '',
  'bool ThirtyFlagsBossWantsBoss(int theFlag)',
  '{',
  '    return theFlag == TF_BOSS_FLAG;',
  '}',
  '',
  'bool ThirtyFlagsBossIsEmpActive()',
  '{',
  '    return ThirtyFlagsMode() && gThirtyFlags.mBossEmpTimer > 0;',
  '}',
  '',
  'bool ThirtyFlagsBossIsDomainActive()',
  '{',
  '    return ThirtyFlagsMode() && gThirtyFlags.mBossDomainTimer > 0;',
  '}',
  '',
  'static int TFBossPhaseForHealth(Zombie* theBoss)',
  '{',
  '    if (!theBoss || theBoss->mBodyMaxHealth <= 0)',
  '        return 1;',
  '',
  '    int aPercent = theBoss->mBodyHealth * 100 / theBoss->mBodyMaxHealth;',
  '    if (aPercent <= TF_BOSS_PHASE3_PERCENT)',
  '        return 3;',
  '    if (aPercent <= TF_BOSS_PHASE2_PERCENT)',
  '        return 2;',
  '    return 1;',
  '}',
  '',
  '// Frames until the next skill for the given phase.',
  'static int TFBossSkillInterval(int thePhase, int theSkill)',
  '{',
  '    switch (theSkill)',
  '    {',
  '    case TF_BOSS_SKILL_SLAM:     return TF_BOSS_SLAM_INTERVAL;',
  '    case TF_BOSS_SKILL_HORDE:    return TF_BOSS_HORDE_INTERVAL;',
  '    case TF_BOSS_SKILL_TERRAIN:  return TF_BOSS_TERRAIN_INTERVAL;',
  '    case TF_BOSS_SKILL_EMP:      return 1200;',
  '    case TF_BOSS_SKILL_ROAR:     return TF_BOSS_ROAR_INTERVAL;',
  '    case TF_BOSS_SKILL_ROAR_ULTIMATE: return TF_BOSS_ROAR_INTERVAL;',
  '    case TF_BOSS_SKILL_DOMAIN:   return TF_BOSS_DOMAIN_INTERVAL;',
  '    default:                     return 600;',
  '    }',
  '}',
  '',
  '// Pick the next skill for a phase (alternates its two signature skills).',
  'static int TFBossPickSkill(int thePhase, int theLastSkill)',
  '{',
  '    if (thePhase == 1)',
  '        return (theLastSkill == TF_BOSS_SKILL_SLAM) ? TF_BOSS_SKILL_HORDE : TF_BOSS_SKILL_SLAM;',
  '    if (thePhase == 2)',
  '    {',
  '        if (theLastSkill == TF_BOSS_SKILL_TERRAIN) return TF_BOSS_SKILL_EMP;',
  '        if (theLastSkill == TF_BOSS_SKILL_EMP)     return TF_BOSS_SKILL_ROAR;',
  '        return TF_BOSS_SKILL_TERRAIN;',
  '    }',
  '    if (theLastSkill == TF_BOSS_SKILL_ROAR_ULTIMATE) return TF_BOSS_SKILL_DOMAIN;',
  '    if (theLastSkill == TF_BOSS_SKILL_DOMAIN)        return TF_BOSS_SKILL_ROAR_ULTIMATE;',
  '    return TF_BOSS_SKILL_ROAR_ULTIMATE;',
  '}',
  '',
  'static void TFBossSummonBoss(Board* theBoard)',
  '{',
  '    Zombie* aBoss = theBoard->AddZombieInRow(ZOMBIE_BOSS, Rand(TF_LAWN_ROWS), theBoard->mCurrentWave);',
  '    if (!aBoss)',
  '        return;',
  '',
  '    aBoss->mBodyHealth = TF_BOSS_HEALTH;',
  '    aBoss->mBodyMaxHealth = TF_BOSS_HEALTH;',
  '    gThirtyFlags.mBossID = aBoss->mZombieID;',
  '    gThirtyFlags.mBossPhase = 1;',
  '    gThirtyFlags.mBossSkillTimer = TF_BOSS_SLAM_INTERVAL;',
  '    gThirtyFlags.mBossSelfDestruct = 0;',
  '}',
  '',
  '// P1 slam: crush a 2x2 block of plants just in front of the boss.',
  'static void TFBossDoSlam(Board* theBoard, Zombie* theBoss, int theRow)',
  '{',
  '    int aCol = TFClampI(theBoard->PixelToGridX((int)theBoss->mPosX, (int)theBoss->mPosY), 0, MAX_GRID_SIZE_X - 1);',
  '    int aMinCol = max(0, aCol - 2);',
  '    for (int aC = aMinCol; aC <= aMinCol + 1 && aC < MAX_GRID_SIZE_X; aC++)',
  '    {',
  '        for (int aR = theRow; aR <= theRow + 1 && aR < TF_LAWN_ROWS; aR++)',
  '        {',
  '            Plant* aPlant = theBoard->GetTopPlantAt(aC, aR, TOPPLANT_ANY);',
  '            if (aPlant && !aPlant->mDead)',
  '                aPlant->Die();',
  '        }',
  '    }',
  '',
  '    int aPixelX = theBoard->GridToPixelX(aMinCol, theRow);',
  '    int aPixelY = theBoard->GridToPixelY(aMinCol, theRow);',
  '    theBoard->KillAllPlantsInRadius(aPixelX, aPixelY, 60);',
  '    theBoard->mApp->PlayFoley(FOLEY_THUNDER);',
  '}',
  '',
  '// P1 horde: six elites split across two lanes.',
  'static void TFBossDoHorde(Board* theBoard, int theRow)',
  '{',
  '    static const ZombieType aPool[] = { ZOMBIE_NORMAL, ZOMBIE_PAIL, ZOMBIE_FOOTBALL, ZOMBIE_GARGANTUAR, ZOMBIE_DOOR, ZOMBIE_LADDER };',
  '    int aOtherRow = (theRow + 2) % TF_LAWN_ROWS;',
  '',
  '    for (int i = 0; i < 6; i++)',
  '    {',
  '        int aRow = (i % 2 == 0) ? theRow : aOtherRow;',
  '        Zombie* aZombie = theBoard->AddZombieInRow(aPool[Rand(6)], aRow, theBoard->mCurrentWave);',
  '        if (!aZombie)',
  '            continue;',
  '',
  '        // reuse the elite path so summoned zombies carry the same modifiers',
  '        ThirtyFlagsZombieInit(aZombie);',
  '        aZombie->mPosX = (float)(MAX_GRID_SIZE_X * 80 + 40 + i * 20);',
  '    }',
  '}',
  '',
  '// P2 terrain: turn a row into water; anything without a lilypad drowns.',
  'static void TFBossDoTerrain(Board* theBoard, int theRow)',
  '{',
  '    theBoard->mPlantRow[theRow] = PLANTROW_POOL;',
  '    for (int aC = 0; aC < MAX_GRID_SIZE_X; aC++)',
  '    {',
  '        theBoard->mGridSquareType[aC][theRow] = GRIDSQUARE_POOL;',
  '',
  '        Plant* aPlant = theBoard->GetTopPlantAt(aC, theRow, TOPPLANT_ANY);',
  '        if (aPlant && !aPlant->mDead && aPlant->mSeedType != SEED_LILYPAD && aPlant->mSeedType != SEED_TANGLEKELP)',
  '            aPlant->Die();',
  '    }',
  '',
  '    gThirtyFlags.mWaterRows |= (1 << theRow);',
  '    gThirtyFlags.mWaterCols = MAX_GRID_SIZE_X;',
  '}',
  '',
  '// P3 ultimate: destroy every plant in the frontmost occupied column.',
  'static void TFBossDoRoarUltimate(Board* theBoard)',
  '{',
  '    int aFrontCol = -1;',
  '    for (int aC = 0; aC < MAX_GRID_SIZE_X && aFrontCol < 0; aC++)',
  '    {',
  '        for (int aR = 0; aR < TF_LAWN_ROWS; aR++)',
  '        {',
  '            Plant* aPlant = theBoard->GetTopPlantAt(aC, aR, TOPPLANT_ANY);',
  '            if (aPlant && !aPlant->mDead)',
  '            {',
  '                aFrontCol = aC;',
  '                break;',
  '            }',
  '        }',
  '    }',
  '',
  '    if (aFrontCol < 0)',
  '        return;',
  '',
  '    for (int aR = 0; aR < TF_LAWN_ROWS; aR++)',
  '    {',
  '        Plant* aPlant = theBoard->GetTopPlantAt(aFrontCol, aR, TOPPLANT_ANY);',
  '        if (aPlant && !aPlant->mDead)',
  '            aPlant->Die();',
  '    }',
  '    theBoard->mApp->PlayFoley(FOLEY_THUNDER);',
  '}',
  '',
  '// Execute a telegraphed skill.',
  'static void TFBossExecuteSkill(Board* theBoard, Zombie* theBoss, int theSkill, int theRow)',
  '{',
  '    switch (theSkill)',
  '    {',
  '    case TF_BOSS_SKILL_SLAM:',
  '        TFBossDoSlam(theBoard, theBoss, theRow);',
  '        break;',
  '',
  '    case TF_BOSS_SKILL_HORDE:',
  '        TFBossDoHorde(theBoard, theRow);',
  '        break;',
  '',
  '    case TF_BOSS_SKILL_TERRAIN:',
  '        TFBossDoTerrain(theBoard, theRow);',
  '        break;',
  '',
  '    case TF_BOSS_SKILL_EMP:',
  '        gThirtyFlags.mBossEmpTimer = TF_BOSS_EMP_FRAMES;',
  '        break;',
  '',
  '    case TF_BOSS_SKILL_ROAR:',
  '        gThirtyFlags.mBossRoarTimer = TF_BOSS_ROAR_FRAMES;',
  '        break;',
  '',
  '    case TF_BOSS_SKILL_ROAR_ULTIMATE:',
  '        TFBossDoRoarUltimate(theBoard);',
  '        break;',
  '',
  '    case TF_BOSS_SKILL_DOMAIN:',
  '        gThirtyFlags.mBossDomainTimer = TF_BOSS_ROAR_FRAMES;',
  '        break;',
  '',
  '    default:',
  '        break;',
  '    }',
  '}',
  '',
  'void ThirtyFlagsBossUpdate(Board* theBoard)',
  '{',
  '    if (!ThirtyFlagsMode() || !theBoard)',
  '        return;',
  '',
  '    int aFlag = ThirtyFlagsCurrentFlag(theBoard);',
  '',
  '    // spawn on the final flag',
  '    if (gThirtyFlags.mBossPhase == 0)',
  '    {',
  '        if (!ThirtyFlagsBossWantsBoss(aFlag))',
  '            return;',
  '        TFBossSummonBoss(theBoard);',
  '        return;',
  '    }',
  '',
  '    Zombie* aBoss = theBoard->ZombieTryToGet(gThirtyFlags.mBossID);',
  '    if (!aBoss || aBoss->mDead)',
  '    {',
  '        gThirtyFlags.mBossPhase = 0;',
  '        gThirtyFlags.mBossID = -1;',
  '        return;',
  '    }',
  '',
  '    // phase transition (with a brief invulnerable window)',
  '    int aWantPhase = TFBossPhaseForHealth(aBoss);',
  '    if (aWantPhase > gThirtyFlags.mBossPhase)',
  '    {',
  '        gThirtyFlags.mBossPhase = aWantPhase;',
  '        gThirtyFlags.mBossSkillTimer = TFBossSkillInterval(aWantPhase, TF_BOSS_SKILL_NONE);',
  '        gThirtyFlags.mBossWarnTimer = 0;',
  '        theBoard->mApp->PlayFoley(FOLEY_THUNDER);',
  '    }',
  '',
  '    // P3 self destruct countdown',
  '    if (gThirtyFlags.mBossPhase == 3)',
  '    {',
  '        int aPercent = aBoss->mBodyHealth * 100 / max(1, aBoss->mBodyMaxHealth);',
  '        if (aPercent <= TF_BOSS_SELF_DESTRUCT_PERCENT && gThirtyFlags.mBossSelfDestruct == 0)',
  '            gThirtyFlags.mBossSelfDestruct = TF_BOSS_SELF_DESTRUCT_FRAMES;',
  '',
  '        if (gThirtyFlags.mBossSelfDestruct > 0)',
  '        {',
  '            gThirtyFlags.mBossSelfDestruct--;',
  '            if (gThirtyFlags.mBossSelfDestruct == 0)',
  '            {',
  '                theBoard->mApp->PlayFoley(FOLEY_LOSE_MUSIC);',
  '                theBoard->mNextWaveCounter = 0;',
  '            }',
  '        }',
  '    }',
  '',
  '    // skill timers',
  '    if (gThirtyFlags.mBossEmpTimer > 0)',
  '        gThirtyFlags.mBossEmpTimer--;',
  '    if (gThirtyFlags.mBossRoarTimer > 0)',
  '        gThirtyFlags.mBossRoarTimer--;',
  '    if (gThirtyFlags.mBossDomainTimer > 0)',
  '        gThirtyFlags.mBossDomainTimer--;',
  '',
  '    // telegraph resolves first',
  '    if (gThirtyFlags.mBossWarnTimer > 0)',
  '    {',
  '        gThirtyFlags.mBossWarnTimer--;',
  '        if (gThirtyFlags.mBossWarnTimer == 0)',
  '        {',
  '            TFBossExecuteSkill(theBoard, aBoss, gThirtyFlags.mBossWarnSkill, gThirtyFlags.mBossWarnRow);',
  '            gThirtyFlags.mBossSkillTimer = TFBossSkillInterval(gThirtyFlags.mBossPhase, gThirtyFlags.mBossWarnSkill);',
  '            gThirtyFlags.mBossWarnSkill = TF_BOSS_SKILL_NONE;',
  '        }',
  '        return;',
  '    }',
  '',
  '    if (gThirtyFlags.mBossSkillTimer > 0)',
  '    {',
  '        gThirtyFlags.mBossSkillTimer--;',
  '        return;',
  '    }',
  '',
  '    // start a new telegraph',
  '    int aSkill = TFBossPickSkill(gThirtyFlags.mBossPhase, gThirtyFlags.mBossWarnSkill);',
  '    gThirtyFlags.mBossWarnSkill = aSkill;',
  '    gThirtyFlags.mBossWarnRow = TFClampI(aBoss->mRow, 0, TF_LAWN_ROWS - 1);',
  '    gThirtyFlags.mBossWarnTimer = TF_BOSS_WARN_FRAMES;',
  '}',
  ''
) -join $eol

$txt = $txt.Insert($ai, $bossLines + $eol)
Write-Host "OK boss module inserted"

[System.IO.File]::WriteAllText($file, $txt, $enc)
Write-Host "written"
